spring.application.name=api-gateway
server.port=8080

# Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# Gateway Routes
spring.cloud.gateway.mvc.routes[0].id=music-search-service
spring.cloud.gateway.mvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.mvc.routes[0].predicates[0]=Path=/music/**

spring.cloud.gateway.mvc.routes[1].id=playlist-service
spring.cloud.gateway.mvc.routes[1].uri=http://localhost:8083
spring.cloud.gateway.mvc.routes[1].predicates[0]=Path=/playlist/**

spring.cloud.gateway.mvc.routes[2].id=streaming-service
spring.cloud.gateway.mvc.routes[2].uri=http://localhost:8082
spring.cloud.gateway.mvc.routes[2].predicates[0]=Path=/stream/**

spring.cloud.gateway.mvc.routes[3].id=recommendation-service
spring.cloud.gateway.mvc.routes[3].uri=http://localhost:8084
spring.cloud.gateway.mvc.routes[3].predicates[0]=Path=/recommendation/**
# Swagger UI Aggregation
springdoc.swagger-ui.urls[0].name=Music-Search
springdoc.swagger-ui.urls[0].url=/music/v3/api-docs
springdoc.swagger-ui.urls[1].name=Playlist
springdoc.swagger-ui.urls[1].url=/playlist/v3/api-docs
springdoc.swagger-ui.urls[2].name=Streaming
springdoc.swagger-ui.urls[2].url=/stream/v3/api-docs
springdoc.swagger-ui.urls[3].name=Recommendation
springdoc.swagger-ui.urls[3].url=/recommendation/v3/api-docs
springdoc.swagger-ui.use-root-path=true
